### ISSUE TITLE
Error in the README-md

### ISSUE THREAD

**Issue by carrermarina** [AbelHristodor/pgcronner#1]
I recently started using pgcronner and noticed a discrepancy in the documentation regarding the import statements.

In the README file, the import statement is written as:
from pgcronner import PGCronner, Job

However, in the examples folder, it is written as:
from pgcronner import PgCronner, Job

It seems like there might be a typo in one of these locations, being the correct one PgCronner.

**Comment by AbelHristodor** [comment]
Hi, thanks for letting me know. I fixed the README.

Just to let you know, I've written this project a while ago and I'm not really maintaining it anymore since it was more for learning purposes. I wouldn't advise its use in any production environments. 

Thanks :)
